# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3381de50ab0e031928300e82271b954f22cbb90a62d2583c5f9ef98c7cfaf839a0018b9a52b2ca014fcfe7221cc97d4baa8ba0e81c4fd0cbcdc2ce95dc067d13

test:
  secret_key_base: dfc74252baa8f5cd3840a677d046a426a46305bb312f0e2f87a144188cb1eacfc87fa743930d16a27e9519fc0ca5df442b45978d67e53383c2a46f89609db9d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
